const router = require('express').Router()

const users = require('./users')
const companies = require('./companies')
const stores = require('./stores')
const licences = require('./licences')
const items = require('./items')
const rooms = require('./rooms')
const printers = require('./printers')
const tables = require('./tables')
const vats = require('./vats')
const transactions = require('./transactions')
const coupons = require('./coupons')
const categories = require('./categories')

router.use('/users', users)
router.use('/companies', companies)
router.use('/stores', stores)
router.use('/licences', licences)
router.use('/items', items)
router.use('/rooms', rooms)
router.use('/printers', printers)
router.use('/tables', tables)
router.use('/vats', vats)
router.use('/transactions', transactions)
router.use('/coupons', coupons)
router.use('/categories', categories)

module.exports = router